/**
 * E2E 共用常量与测试素材。
 * 账号与 common/management/commands/seed_e2e.py 保持一致。
 */

export const E2E_USER = "e2e_info";
export const E2E_PLAIN = "e2e_plain";
export const E2E_PASSWORD = process.env.E2E_PASSWORD ?? "e2e-pass-123";

/** 320×200 带图案 PNG（base64 内联，避免二进制 fixture 入库；约 564B）。 */
export const PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAUAAAADICAIAAAAWZq/8AAAB+0lEQVR42u3WQQ0EIRBFQVg/4BAOSARBvSY4AFMlYJJP8tKTIyLtUPtKN5ij2GvvM3t/CbiWgEHAgIABAYOAAQEDAgYEDAIGBAwIGAQMCBgQMCBgEDAgYEDAgIBBwICAAQHDF+XSplcAFxgQMCBgEDAgYEDAgIBBwICAAQGDgAEBAwIGBAwCBgQMCBgQMAgYEDAgYBAwIGBAwICAQcCAgAEBAwIGAQMCBgQMAgYEDAgYEDAIGBAwIGAQMCBgQMCAgEHAgIABAQMCBgEDAgYEDAIGBAwIGBAwCBg4UY6ILR+qfV0xeI5ir73P7HWBwS80IGBAwCBgQMCAgAEBg4ABAQMCBgEDAgYEDAgYBAwIGBAwIGAQMCBgQMAgYOAqubTpFcAFBgQMCBgEDAgYEDAgYBAwIGBAwCBgQMCAgAEBg4ABAQMCBgQMAgYEDAgYBAwIGBAwIGAQMCBgQMCAgEHAgIABAYOAAQEDAgYEDAIGBAwIGAQMCBgQMCBgEDAgYEDAgIBBwICAAQGDgAEBAwIGBAwCBk6UI2LLh2pfVwyeo9hr7zN7XWDwCw0IGBAwCBgQMCBgQMAgYEDAgIBBwICAAQEDAgYBAwIGBAwIGAQMCBgQMAgYuEoubXoFcIEBAQMCBgEDAgYEDAgYBAwIGBAwCBgQMCBgQMAgYOBMfzHDLnOf8AlVAAAAAElFTkSuQmCC";

/** 测试图片 Buffer（封面 / 编辑器插图共用）。 */
export function pngBuffer(): Buffer {
  return Buffer.from(PNG_BASE64, "base64");
}

/** 每次运行唯一的标题，避免历史数据干扰断言。 */
export function uniqueTitle(prefix: string): string {
  return `${prefix} ${Date.now()}`;
}
